fix(tests): Add contains_over_clause #848
An update to django 4.2 has broken the test suite with error
AttributeError: 'ExtraJoinRestriction' object has no attribute 'contains_over_clause'

The `contains_over_clause = False` attribute added to ExtraJoinRestriction solves the error.